# Generated by Django 5.1.4 on 2025-01-04 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(auto_now_add=True, verbose_name='Ngày phản hồi')),
                ('content', models.TextField(verbose_name='Nội dung phản hồi')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Phản hồi từ quản lý')),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=100, verbose_name='Họ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('university', models.CharField(max_length=200, verbose_name='Trường đại học')),
                ('major', models.CharField(max_length=200, verbose_name='Chuyên ngành')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu thực tập')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc thực tập')),
                ('status', models.CharField(choices=[('active', 'Đang thực tập'), ('completed', 'Đã hoàn thành'), ('terminated', 'Đã chấm dứt')], default='active', max_length=20, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Điểm số')),
                ('comments', models.TextField(verbose_name='Nhận xét')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.intern', verbose_name='Thực tập sinh')),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Vị trí tuyển dụng')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('requirements', models.TextField(verbose_name='Yêu cầu')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('deadline', models.DateField(verbose_name='Hạn nộp hồ sơ')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đăng')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('trainer', models.CharField(max_length=200, verbose_name='Người đào tạo')),
                ('interns', models.ManyToManyField(related_name='training_programs', to='home.intern', verbose_name='Thực tập sinh')),
            ],
        ),
        migrations.DeleteModel(
            name='cource',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.AddField(
            model_name='feedback',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.intern', verbose_name='Thực tập sinh'),
        ),
    ]
