# Generated by Django 5.1.4 on 2025-01-17 06:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback_intern_performance_recruitment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Đã giải quyết'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày phản hồi'),
        ),
        migrations.AddField(
            model_name='intern',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='interns/avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='intern',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='intern',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Họ và tên'),
        ),
        migrations.AddField(
            model_name='intern',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='intern',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
        migrations.AddField(
            model_name='performance',
            name='evaluation_period',
            field=models.CharField(default='Kỳ đánh giá mặc định', max_length=100, verbose_name='Kỳ đánh giá'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='is_final_evaluation',
            field=models.BooleanField(default=False, verbose_name='Đánh giá cuối kỳ'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa điểm'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mức lương'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa điểm'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng tối đa'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có định dạng hợp lệ.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Số điện thoại'),
        ),
    ]
