# Generated by Django 5.1.4 on 2025-01-17 08:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_feedback_is_resolved_feedback_response_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Phản hồi', 'verbose_name_plural': 'Phản hồi'},
        ),
        migrations.AlterModelOptions(
            name='intern',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thực tập sinh', 'verbose_name_plural': 'Thực tập sinh'},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'verbose_name': 'Đánh giá hiệu suất', 'verbose_name_plural': 'Đánh giá hiệu suất'},
        ),
        migrations.AlterModelOptions(
            name='recruitment',
            options={'ordering': ['-posted_date'], 'verbose_name': 'Tuyển dụng', 'verbose_name_plural': 'Tuyển dụng'},
        ),
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'ordering': ['-start_date'], 'verbose_name': 'Chương trình đào tạo', 'verbose_name_plural': 'Chương trình đào tạo'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='home.intern', verbose_name='Thực tập sinh'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='email',
            field=models.EmailField(help_text='Nhập địa chỉ email hợp lệ', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='phone',
            field=models.CharField(help_text='Nhập số điện thoại theo định dạng quốc tế, ví dụ: +84123456789', max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có định dạng hợp lệ.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='home.intern', verbose_name='Thực tập sinh'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to=settings.AUTH_USER_MODEL, verbose_name='Người đăng'),
        ),
    ]
