# Generated by Django 5.1.4 on 2025-01-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_intern_is_active_performance_rating_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
