# Generated by Django 5.1.4 on 2025-01-18 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_trainingprogram_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Liên kết'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('error', 'Lỗi'), ('success', 'Thành công')], default='info', max_length=20, verbose_name='Loại thông báo'),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Giờ thực tế'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn chót'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Giờ ước tính'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên phòng ban')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Quản lý')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Phòng ban',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='intern',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interns', to='home.department', verbose_name='Phòng ban'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('location', models.CharField(max_length=200, verbose_name='Địa điểm')),
                ('participants', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Người tham gia')),
            ],
            options={
                'verbose_name': 'Sự kiện',
                'verbose_name_plural': 'Sự kiện',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dự án')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('planned', 'Đã lên kế hoạch'), ('in_progress', 'Đang thực hiện'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='planned', max_length=20, verbose_name='Trạng thái')),
                ('interns', models.ManyToManyField(related_name='projects', to='home.intern', verbose_name='Thực tập sinh')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Quản lý dự án')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.project', verbose_name='Dự án'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nộp')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày đánh giá')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='Nhận xét')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.intern', verbose_name='Thực tập sinh')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Báo cáo',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày điểm danh')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng mặt'), ('late', 'Đến muộn')], default='present', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='home.intern', verbose_name='Thực tập sinh')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Điểm danh',
                'unique_together': {('intern', 'date')},
            },
        ),
    ]
