# Generated by Django 5.1.4 on 2025-01-19 09:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_notification_link_notification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Điểm danh', 'verbose_name_plural': 'Điểm danh'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-feedback_date'], 'verbose_name': 'Phản hồi', 'verbose_name_plural': 'Phản hồi'},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-evaluation_date'], 'verbose_name': 'Đánh giá hiệu suất', 'verbose_name_plural': 'Đánh giá hiệu suất'},
        ),
        migrations.AddField(
            model_name='recruitment',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_final',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Báo cáo cuối kỳ'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tên phòng ban'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã giải quyết'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='interns/avatars/%Y/%m/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='email',
            field=models.EmailField(db_index=True, help_text='Nhập địa chỉ email hợp lệ', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='phone',
            field=models.CharField(db_index=True, help_text='Nhập số điện thoại theo định dạng quốc tế, ví dụ: +84123456789', max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có định dạng hợp lệ.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='status',
            field=models.CharField(choices=[('active', 'Đang thực tập'), ('completed', 'Đã hoàn thành'), ('terminated', 'Đã chấm dứt')], db_index=True, default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã đọc'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Điểm số'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tên dự án'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Đã lên kế hoạch'), ('in_progress', 'Đang thực hiện'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='planned', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tên chương trình'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='active', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
