# Generated by Django 5.1.4 on 2025-01-19 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_attendance_options_alter_feedback_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên ứng viên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('new', 'Ứng viên Mới'), ('interviewed', 'Đã Phỏng vấn')], default='new', max_length=50, verbose_name='Trạng thái')),
                ('applied_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày ứng tuyển')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('score', models.PositiveIntegerField(verbose_name='Điểm số')),
                ('comments', models.TextField(verbose_name='Nhận xét')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.candidate', verbose_name='Ứng viên')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('hrm', 'HRM'), ('lms', 'LMS')], max_length=50, verbose_name='Hệ thống')),
                ('integrated_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tích hợp')),
                ('integrated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tích hợp')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(verbose_name='Ngày phỏng vấn')),
                ('interview_time', models.TimeField(verbose_name='Thời gian phỏng vấn')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.candidate', verbose_name='Ứng viên')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người phỏng vấn')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('platform', models.CharField(choices=[('website', 'Trang web Công ty'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed')], max_length=50, verbose_name='Nền tảng')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đăng')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('hr', 'HR Manager'), ('coordinator', 'Internship Coordinator'), ('mentor', 'Mentor')], max_length=50, verbose_name='Vai trò')),
                ('permission', models.CharField(choices=[('read', 'Chỉ Đọc'), ('write', 'Đọc và Ghi')], max_length=50, verbose_name='Quyền Truy cập')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
    ]
