# Generated by Django 5.1.4 on 2025-02-07 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_jobpost_is_active_alter_interview_candidate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa điểm'),
        ),
        migrations.AddField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.candidate', verbose_name='Ứng viên'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateField(verbose_name='Ngày phỏng vấn'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_time',
            field=models.TimeField(verbose_name='Thời gian phỏng vấn'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người phỏng vấn'),
        ),
    ]
